INSERT INTO food (name, rarity, price, colour)
VALUES
    ('stirred chicken',               1, 1, 07),
    ('birds egg',                     1, 1, 06),
    ('hot wings',                     1, 1, 09),
    ('stargazy pie',                  1, 1, 06),
    ('jello',                         1, 1, 09),
    ('small roast',                   1, 1, 06),
    ('stuffed pigeon',                1, 1, 04),
    ('liver curry',                   1, 1, 13),
    ('meat pie',                      1, 1, 06),
    ('very very hot chili con carne', 1, 1, 09),
    ('stroganoff',                    1, 1, 10),
    ('Surstromming',                  1, 2, 15),
    ('shark fin soup',                1, 2, 10),
    ('baby back ribs',                1, 2, 09),
    ('scone',                         1, 2, 10),
    ('cucumber sandwich',             1, 2, 15),
    ('tripe sandwich',                1, 2, 06),
    ('chowder',                       1, 2, 07),
    ('fried tarantula',               1, 2, 08),
    ('wasp crackers',                 1, 2, 07),
    ('prawn crackers',                1, 2, 10),
    ('egg fried rice',                1, 2, 10),
    ('chicken balls',                 1, 2, 07),
    ('large egg',                     1, 2, 06),
    ('champ',                         1, 2, 10),
    ('spring rolls',                  1, 2, 07),
    ('irish stew',                    1, 2, 06),
    ('haggis',                        1, 2, 06),
    ('white pudding',                 1, 2, 10),
    ('black pudding',                 1, 2, 08),
    ('scrambled eggs on toast',       1, 2, 07),
    ('mutton',                        1, 2, 06),
    ('satued onions',                 1, 2, 06),
    ('jam doughnut',                  1, 2, 06),
    ('cherry cake',                   1, 2, 09),
    ('pierogi',                       1, 2, 07),
    ('biryani',                       1, 2, 07),
    ('kebab',                         1, 2, 07),
    ('burger',                        1, 2, 06),
    ('hotdog',                        1, 2, 06),
    ('potato waffle',                 1, 2, 06),
    ('chip butty',                    1, 2, 10),
    ('stuffed shrooms',               1, 2, 10),
    ('shroom curry',                  1, 2, 06),
    ('curry leaves',                  1, 2, 15),
    ('parma ham',                     1, 2, 02),
    ('bread',                         1, 2, 10),
    ('whiskey',                       1, 2, 06),
    ('tea',                           1, 2, 06),
    ('vodka',                         1, 2, 01),
    ('mead',                          1, 2, 07),
    ('honey',                         1, 2, 07),
    ('beer',                          1, 2, 06),
    ('chips',                         1, 2, 07),
    ('cranberry braggot',             1, 2, 09),
    ('strawbeery wine',               1, 2, 02),
    ('madras',                        1, 2, 06),
    ('vindaloo',                      1, 2, 06),
    ('fugu',                          1, 2, 10),
    ('muktuk',                        1, 2, 06),
    ('bunny chow',                    1, 2, 06),
    ('frogs legs',                    1, 2, 15),
    ('scallions',                     1, 2, 15),
    ('scampi',                        1, 2, 10),
    ('langoustine',                   1, 2, 10),
    ('liver and onions',              1, 2, 13),
    ('chicken and sweetcorn soup',    1, 2, 07),
    ('carbonara',                     1, 2, 10),
    ('spaghetti and meatballs',       1, 2, 06),
    ('garlic_bread',                  1, 2, 07),
    ('kung pao',                      1, 2, 09),
    ('fu yung',                       1, 2, 07),
    ('porridge',                      1, 2, 04);
