from sql.generate.element.element_list import element_list
from sql.generate.element.element_effectiveness.element_effectiveness_type.element_effectiveness_type_list import element_effectiveness_type_list

t = {element_effectiveness_type[0]: index+1 for index, element_effectiveness_type in enumerate(element_effectiveness_type_list)}

e = {element[0]: index+1 for index, element in enumerate(element_list)}

element_effectiveness_list = [
    (e["alien"], e["alien"], t["weak"]),
    (e["alien"], e["air"], t["somewhat weak"]),
    (e["alien"], e["chaos"], t["strong"]),
    (e["alien"], e["earth"], t["neutral"]),
    (e["alien"], e["electricity"], t["neutral"]),
    (e["alien"], e["evil"], t["neutral"]),
    (e["alien"], e["fire"], t["neutral"]),
    (e["alien"], e["holiness"], t["neutral"]),
    (e["alien"], e["ice"], t["neutral"]),
    (e["alien"], e["metal"], t["neutral"]),
    (e["alien"], e["mutation"], t["very weak"]),
    (e["alien"], e["normal"], t["strong"]),
    (e["alien"], e["plant"], t["weak"]),
    (e["alien"], e["poison"], t["neutral"]),
    (e["alien"], e["radiation"], t["somewhat strong"]),
    (e["alien"], e["undead"], t["neutral"]),
    (e["alien"], e["water"], t["neutral"]),
    (e["alien"], e["fungus"], t["neutral"]),
    
    (e["air"], e["alien"], t["weak"]),
    (e["air"], e["air"], t["weak"]),
    (e["air"], e["chaos"], t["neutral"]),
    (e["air"], e["earth"], t["somewhat strong"]),
    (e["air"], e["electricity"], t["somewhat weak"]),
    (e["air"], e["evil"], t["neutral"]),
    (e["air"], e["fire"], t["somewhat strong"]),
    (e["air"], e["holiness"], t["neutral"]),
    (e["air"], e["ice"], t["neutral"]),
    (e["air"], e["metal"], t["weak"]),
    (e["air"], e["mutation"], t["strong"]),
    (e["air"], e["normal"], t["somewhat strong"]),
    (e["air"], e["plant"], t["very strong"]),
    (e["air"], e["poison"], t["neutral"]),
    (e["air"], e["radiation"], t["strong"]),
    (e["air"], e["undead"], t["neutral"]),
    (e["air"], e["water"], t["neutral"]),
    (e["air"], e["fungus"], t["neutral"]),

    (e["chaos"], e["alien"], t["weak"]),
    (e["chaos"], e["air"], t["neutral"]),
    (e["chaos"], e["chaos"], t["very strong"]),
    (e["chaos"], e["earth"], t["strong"]),
    (e["chaos"], e["electricity"], t["somewhat strong"]),
    (e["chaos"], e["evil"], t["weak"]),
    (e["chaos"], e["fire"], t["neutral"]),
    (e["chaos"], e["holiness"], t["strong"]),
    (e["chaos"], e["ice"], t["somewhat weak"]),
    (e["chaos"], e["metal"], t["weak"]),
    (e["chaos"], e["mutation"], t["strong"]),
    (e["chaos"], e["normal"], t["strong"]),
    (e["chaos"], e["plant"], t["weak"]),
    (e["chaos"], e["poison"], t["neutral"]),
    (e["chaos"], e["radiation"], t["strong"]),
    (e["chaos"], e["undead"], t["neutral"]),
    (e["chaos"], e["water"], t["weak"]),
    (e["chaos"], e["fungus"], t["somewhat strong"]),

    (e["earth"], e["alien"], t["neutral"]),
    (e["earth"], e["air"], t["very weak"]),
    (e["earth"], e["chaos"], t["neutral"]),
    (e["earth"], e["earth"], t["weak"]),
    (e["earth"], e["electricity"], t["very strong"]),
    (e["earth"], e["evil"], t["neutral"]),
    (e["earth"], e["fire"], t["strong"]),
    (e["earth"], e["holiness"], t["neutral"]),
    (e["earth"], e["ice"], t["somewhat strong"]),
    (e["earth"], e["metal"], t["strong"]),
    (e["earth"], e["mutation"], t["neutral"]),
    (e["earth"], e["normal"], t["neutral"]),
    (e["earth"], e["plant"], t["weak"]),
    (e["earth"], e["poison"], t["strong"]),
    (e["earth"], e["radiation"], t["somewhat weak"]),
    (e["earth"], e["undead"], t["neutral"]),
    (e["earth"], e["water"], t["weak"]),
    (e["earth"], e["fungus"], t["weak"]),

    (e["electricity"], e["alien"], t["neutral"]),
    (e["electricity"], e["air"], t["somewhat strong"]),
    (e["electricity"], e["chaos"], t["neutral"]),
    (e["electricity"], e["earth"], t["very weak"]),
    (e["electricity"], e["electricity"], t["weak"]),
    (e["electricity"], e["evil"], t["neutral"]),
    (e["electricity"], e["fire"], t["somewhat weak"]),
    (e["electricity"], e["holiness"], t["neutral"]),
    (e["electricity"], e["ice"], t["somewhat strong"]),
    (e["electricity"], e["metal"], t["strong"]),
    (e["electricity"], e["mutation"], t["neutral"]),
    (e["electricity"], e["normal"], t["neutral"]),
    (e["electricity"], e["plant"], t["somewhat weak"]),
    (e["electricity"], e["poison"], t["neutral"]),
    (e["electricity"], e["radiation"], t["somewhat weak"]),
    (e["electricity"], e["undead"], t["somewhat weak"]),
    (e["electricity"], e["water"], t["very strong"]),
    (e["electricity"], e["fungus"], t["somewhat weak"]),

    (e["evil"], e["alien"], t["neutral"]),
    (e["evil"], e["air"], t["somewhat weak"]),
    (e["evil"], e["chaos"], t["strong"]),
    (e["evil"], e["earth"], t["somewhat strong"]),
    (e["evil"], e["electricity"], t["neutral"]),
    (e["evil"], e["evil"], t["neutral"]),
    (e["evil"], e["fire"], t["somewhat strong"]),
    (e["evil"], e["holiness"], t["very strong"]),
    (e["evil"], e["ice"], t["somewhat strong"]),
    (e["evil"], e["metal"], t["somewhat weak"]),
    (e["evil"], e["mutation"], t["neutral"]),
    (e["evil"], e["normal"], t["somewhat strong"]),
    (e["evil"], e["plant"], t["weak"]),
    (e["evil"], e["poison"], t["somewhat strong"]),
    (e["evil"], e["radiation"], t["neutral"]),
    (e["evil"], e["undead"], t["neutral"]),
    (e["evil"], e["water"], t["weak"]),
    (e["evil"], e["fungus"], t["neutral"]),

    (e["fire"], e["alien"], t["neutral"]),
    (e["fire"], e["air"], t["somewhat weak"]),
    (e["fire"], e["chaos"], t["neutral"]),
    (e["fire"], e["earth"], t["very weak"]),
    (e["fire"], e["electricity"], t["neutral"]),
    (e["fire"], e["evil"], t["weak"]),
    (e["fire"], e["fire"], t["weak"]),
    (e["fire"], e["holiness"], t["somewhat strong"]),
    (e["fire"], e["ice"], t["strong"]),
    (e["fire"], e["metal"], t["strong"]),
    (e["fire"], e["mutation"], t["somewhat strong"]),
    (e["fire"], e["normal"], t["somewhat strong"]),
    (e["fire"], e["plant"], t["very strong"]),
    (e["fire"], e["poison"], t["neutral"]),
    (e["fire"], e["radiation"], t["somewhat weak"]),
    (e["fire"], e["undead"], t["strong"]),
    (e["fire"], e["water"], t["very weak"]),
    (e["fire"], e["fungus"], t["strong"]),

    (e["holiness"], e["alien"], t["somewhat strong"]),
    (e["holiness"], e["air"], t["neutral"]),
    (e["holiness"], e["chaos"], t["weak"]),
    (e["holiness"], e["earth"], t["neutral"]),
    (e["holiness"], e["electricity"], t["neutral"]),
    (e["holiness"], e["evil"], t["very strong"]),
    (e["holiness"], e["fire"], t["somewhat weak"]),
    (e["holiness"], e["holiness"], t["neutral"]),
    (e["holiness"], e["ice"], t["somewhat weak"]),
    (e["holiness"], e["metal"], t["somewhat strong"]),
    (e["holiness"], e["mutation"], t["somewhat strong"]),
    (e["holiness"], e["normal"], t["somewhat strong"]),
    (e["holiness"], e["plant"], t["neutral"]),
    (e["holiness"], e["poison"], t["weak"]),
    (e["holiness"], e["radiation"], t["neutral"]),
    (e["holiness"], e["undead"], t["weak"]),
    (e["holiness"], e["water"], t["neutral"]),
    (e["holiness"], e["fungus"], t["somewhat weak"]),

    (e["ice"], e["alien"], t["somewhat strong"]),
    (e["ice"], e["air"], t["somewhat weak"]),
    (e["ice"], e["chaos"], t["somewhat strong"]),
    (e["ice"], e["earth"], t["somewhat strong"]),
    (e["ice"], e["electricity"], t["neutral"]),
    (e["ice"], e["evil"], t["somewhat strong"]),
    (e["ice"], e["fire"], t["very weak"]),
    (e["ice"], e["holiness"], t["weak"]),
    (e["ice"], e["ice"], t["weak"]),
    (e["ice"], e["metal"], t["very weak"]),
    (e["ice"], e["mutation"], t["strong"]),
    (e["ice"], e["normal"], t["weak"]),
    (e["ice"], e["plant"], t["very strong"]),
    (e["ice"], e["poison"], t["neutral"]),
    (e["ice"], e["radiation"], t["weak"]),
    (e["ice"], e["undead"], t["strong"]),
    (e["ice"], e["water"], t["somewhat strong"]),
    (e["ice"], e["fungus"], t["very strong"]),

    (e["metal"], e["alien"], t["strong"]),
    (e["metal"], e["air"], t["strong"]),
    (e["metal"], e["chaos"], t["weak"]),
    (e["metal"], e["earth"], t["somewhat strong"]),
    (e["metal"], e["electricity"], t["very weak"]),
    (e["metal"], e["evil"], t["neutral"]),
    (e["metal"], e["fire"], t["very weak"]),
    (e["metal"], e["holiness"], t["neutral"]),
    (e["metal"], e["ice"], t["strong"]),
    (e["metal"], e["metal"], t["weak"]),
    (e["metal"], e["mutation"], t["somewhat strong"]),
    (e["metal"], e["normal"], t["neutral"]),
    (e["metal"], e["plant"], t["weak"]),
    (e["metal"], e["poison"], t["somewhat strong"]),
    (e["metal"], e["radiation"], t["strong"]),
    (e["metal"], e["undead"], t["strong"]),
    (e["metal"], e["water"], t["weak"]),
    (e["metal"], e["fungus"], t["strong"]),

    (e["mutation"], e["alien"], t["somewhat strong"]),
    (e["mutation"], e["air"], t["weak"]),
    (e["mutation"], e["chaos"], t["weak"]),
    (e["mutation"], e["earth"], t["somewhat weak"]),
    (e["mutation"], e["electricity"], t["neutral"]),
    (e["mutation"], e["evil"], t["neutral"]),
    (e["mutation"], e["fire"], t["weak"]),
    (e["mutation"], e["holiness"], t["somewhat strong"]),
    (e["mutation"], e["ice"], t["neutral"]),
    (e["mutation"], e["metal"], t["somewhat weak"]),
    (e["mutation"], e["mutation"], t["somewhat strong"]),
    (e["mutation"], e["normal"], t["very strong"]),
    (e["mutation"], e["plant"], t["neutral"]),
    (e["mutation"], e["poison"], t["somewhat strong"]),
    (e["mutation"], e["radiation"], t["very weak"]),
    (e["mutation"], e["undead"], t["neutral"]),
    (e["mutation"], e["water"], t["somewhat strong"]),
    (e["mutation"], e["fungus"], t["somewhat strong"]),

    (e["normal"], e["alien"], t["somewhat weak"]),
    (e["normal"], e["air"], t["neutral"]),
    (e["normal"], e["chaos"], t["somewhat weak"]),
    (e["normal"], e["earth"], t["neutral"]),
    (e["normal"], e["electricity"], t["neutral"]),
    (e["normal"], e["evil"], t["neutral"]),
    (e["normal"], e["fire"], t["neutral"]),
    (e["normal"], e["holiness"], t["somewhat strong"]),
    (e["normal"], e["ice"], t["neutral"]),
    (e["normal"], e["metal"], t["somewhat weak"]),
    (e["normal"], e["mutation"], t["somewhat weak"]),
    (e["normal"], e["normal"], t["somewhat weak"]),
    (e["normal"], e["plant"], t["neutral"]),
    (e["normal"], e["poison"], t["neutral"]),
    (e["normal"], e["radiation"], t["very weak"]),
    (e["normal"], e["undead"], t["somewhat weak"]),
    (e["normal"], e["water"], t["neutral"]),
    (e["normal"], e["fungus"], t["neutral"]),

    (e["plant"], e["alien"], t["somewhat strong"]),
    (e["plant"], e["air"], t["somewhat weak"]),
    (e["plant"], e["chaos"], t["neutral"]),
    (e["plant"], e["earth"], t["strong"]),
    (e["plant"], e["electricity"], t["weak"]),
    (e["plant"], e["evil"], t["neutral"]),
    (e["plant"], e["fire"], t["very weak"]),
    (e["plant"], e["holiness"], t["neutral"]),
    (e["plant"], e["ice"], t["weak"]),
    (e["plant"], e["metal"], t["somewhat weak"]),
    (e["plant"], e["mutation"], t["neutral"]),
    (e["plant"], e["normal"], t["neutral"]),
    (e["plant"], e["plant"], t["weak"]),
    (e["plant"], e["poison"], t["somewhat weak"]),
    (e["plant"], e["radiation"], t["somewhat weak"]),
    (e["plant"], e["undead"], t["somewhat strong"]),
    (e["plant"], e["water"], t["very strong"]),
    (e["plant"], e["fungus"], t["neutral"]),

    (e["poison"], e["alien"], t["somewhat strong"]),
    (e["poison"], e["air"], t["weak"]),
    (e["poison"], e["chaos"], t["somewhat strong"]),
    (e["poison"], e["earth"], t["weak"]),
    (e["poison"], e["electricity"], t["neutral"]),
    (e["poison"], e["evil"], t["neutral"]),
    (e["poison"], e["fire"], t["neutral"]),
    (e["poison"], e["holiness"], t["strong"]),
    (e["poison"], e["ice"], t["weak"]),
    (e["poison"], e["metal"], t["very weak"]),
    (e["poison"], e["mutation"], t["somewhat strong"]),
    (e["poison"], e["normal"], t["strong"]),
    (e["poison"], e["plant"], t["weak"]),
    (e["poison"], e["poison"], t["weak"]),
    (e["poison"], e["radiation"], t["somewhat weak"]),
    (e["poison"], e["undead"], t["weak"]),
    (e["poison"], e["water"], t["strong"]),
    (e["poison"], e["fungus"], t["somewhat weak"]),

    (e["radiation"], e["alien"], t["somewhat strong"]),
    (e["radiation"], e["air"], t["neutral"]),
    (e["radiation"], e["chaos"], t["very weak"]),
    (e["radiation"], e["earth"], t["weak"]),
    (e["radiation"], e["electricity"], t["neutral"]),
    (e["radiation"], e["evil"], t["somewhat strong"]),
    (e["radiation"], e["fire"], t["neutral"]),
    (e["radiation"], e["holiness"], t["somewhat strong"]),
    (e["radiation"], e["ice"], t["neutral"]),
    (e["radiation"], e["metal"], t["weak"]),
    (e["radiation"], e["mutation"], t["very strong"]),
    (e["radiation"], e["normal"], t["strong"]),
    (e["radiation"], e["plant"], t["strong"]),
    (e["radiation"], e["poison"], t["somewhat weak"]),
    (e["radiation"], e["radiation"], t["very strong"]),
    (e["radiation"], e["undead"], t["somewhat weak"]),
    (e["radiation"], e["water"], t["somewhat weak"]),
    (e["radiation"], e["fungus"], t["somewhat weak"]),

    (e["undead"], e["alien"], t["strong"]),
    (e["undead"], e["air"], t["neutral"]),
    (e["undead"], e["chaos"], t["strong"]),
    (e["undead"], e["earth"], t["weak"]),
    (e["undead"], e["electricity"], t["weak"]),
    (e["undead"], e["evil"], t["strong"]),
    (e["undead"], e["fire"], t["weak"]),
    (e["undead"], e["holiness"], t["strong"]),
    (e["undead"], e["ice"], t["weak"]),
    (e["undead"], e["metal"], t["weak"]),
    (e["undead"], e["mutation"], t["strong"]),
    (e["undead"], e["normal"], t["very strong"]),
    (e["undead"], e["plant"], t["weak"]),
    (e["undead"], e["poison"], t["strong"]),
    (e["undead"], e["radiation"], t["weak"]),
    (e["undead"], e["undead"], t["neutral"]),
    (e["undead"], e["water"], t["weak"]),
    (e["undead"], e["fungus"], t["weak"]),

    (e["water"], e["alien"], t["strong"]),
    (e["water"], e["air"], t["somewhat strong"]),
    (e["water"], e["chaos"], t["neutral"]),
    (e["water"], e["earth"], t["very strong"]),
    (e["water"], e["electricity"], t["weak"]),
    (e["water"], e["evil"], t["neutral"]),
    (e["water"], e["fire"], t["weak"]),
    (e["water"], e["holiness"], t["neutral"]),
    (e["water"], e["ice"], t["somewhat strong"]),
    (e["water"], e["metal"], t["neutral"]),
    (e["water"], e["mutation"], t["neutral"]),
    (e["water"], e["normal"], t["neutral"]),
    (e["water"], e["plant"], t["very weak"]),
    (e["water"], e["poison"], t["somewhat strong"]),
    (e["water"], e["radiation"], t["neutral"]),
    (e["water"], e["undead"], t["neutral"]),
    (e["water"], e["water"], t["weak"]),
    (e["water"], e["fungus"], t["somewhat weak"]),

    (e["fungus"], e["alien"], t["weak"]),
    (e["fungus"], e["air"], t["neutral"]),
    (e["fungus"], e["chaos"], t["somewhat strong"]),
    (e["fungus"], e["earth"], t["somewhat strong"]),
    (e["fungus"], e["electricity"], t["neutral"]),
    (e["fungus"], e["evil"], t["neutral"]),
    (e["fungus"], e["fire"], t["very weak"]),
    (e["fungus"], e["holiness"], t["neutral"]),
    (e["fungus"], e["ice"], t["very weak"]),
    (e["fungus"], e["metal"], t["very weak"]),
    (e["fungus"], e["mutation"], t["somewhat strong"]),
    (e["fungus"], e["normal"], t["weak"]),
    (e["fungus"], e["plant"], t["somewhat strong"]),
    (e["fungus"], e["poison"], t["somewhat strong"]),
    (e["fungus"], e["radiation"], t["weak"]),
    (e["fungus"], e["undead"], t["somewhat strong"]),
    (e["fungus"], e["water"], t["somewhat strong"]),
    (e["fungus"], e["fungus"], t["somewhat strong"])
 ]   
