INSERT INTO element(name, type, colour)
VALUES
    ('typeless',    1, 01),
    ('alien',       3, 02),
    ('air',         3, 03),
    ('chaos',       2, 04),
    ('earth',       2, 05),
    ('electricity', 3, 06),
    ('evil',        2, 07),
    ('fire',        3, 08),
    ('holiness',    2, 09),
    ('ice',         3, 10),
    ('metal',       2, 11),
    ('mutation',    2, 12),
    ('normal',      2 ,13),
    ('plant',       3, 14),
    ('poison',      2, 15),
    ('radiation',   3, 16),
    ('undead',      2, 17),
    ('water',       3, 18);
