# colour list (1) pink (2) magenta (3) silver (4) orange (5) brown (6) yellow (7) black (8) red (9) white
# (10) cyan (11) dark grey (12) maroon (13)

from sql.generate.colour.colour_main.colour_list import colour_list
from sql.generate.colour.colour_adjective.colour_adjective_list import colour_adjective_list

a = {adj: index + 1 for index, adj in enumerate(colour_adjective_list)}
c = {color[0]: index+1 for index, color in enumerate(colour_list)}

colour_adjective_fill_list = [
    (a["aerial"], c["blue"]),

    (a["aesthetic"], c["pink"]),
    (a["aesthetic"], c["magenta"]),
    (a["aesthetic"], c["silver"]),
    (a["aesthetic"], c["orange"]),
    (a["aesthetic"], c["brown"]),
    (a["aesthetic"], c["yellow"]),
    (a["aesthetic"], c["black"]),
    (a["aesthetic"], c["red"]),
    (a["aesthetic"], c["white"]),
    (a["aesthetic"], c["cyan"]),
    (a["aesthetic"], c["dark grey"]),
    (a["aesthetic"], c["maroon"]),
    (a["aesthetic"], c["grey"]),
    (a["aesthetic"], c["green"]),
    (a["aesthetic"], c["purple"]),
    (a["aesthetic"], c["lime"]),
    (a["aesthetic"], c["dark green"]),
    (a["aesthetic"], c["blue"]),
    (a["aesthetic"], c["gold"]),

    (a["angelic"], c["white"]),

    (a["astonishing"], c["pink"]),
    (a["astonishing"], c["magenta"]),
    (a["astonishing"], c["silver"]),
    (a["astonishing"], c["orange"]),
    (a["astonishing"], c["yellow"]),
    (a["astonishing"], c["black"]),
    (a["astonishing"], c["red"]),
    (a["astonishing"], c["white"]),
    (a["astonishing"], c["cyan"]),
    (a["astonishing"], c["purple"]),
    (a["astonishing"], c["lime"]),
    (a["astonishing"], c["blue"]),
    (a["astonishing"], c["gold"]),

    (a["beautiful"], c["pink"]),
    (a["beautiful"], c["silver"]),
    (a["beautiful"], c["brown"]),
    (a["beautiful"], c["black"]),
    (a["beautiful"], c["red"]),
    (a["beautiful"], c["white"]),
    (a["beautiful"], c["green"]),
    (a["beautiful"], c["purple"]),
    (a["beautiful"], c["blue"]),
    (a["beautiful"], c["gold"]),

    (a["bewildering"], c["pink"]),
    (a["bewildering"], c["magenta"]),
    (a["bewildering"], c["orange"]),
    (a["bewildering"], c["brown"]),
    (a["bewildering"], c["yellow"]),
    (a["bewildering"], c["black"]),
    (a["bewildering"], c["red"]),
    (a["bewildering"], c["cyan"]),
    (a["bewildering"], c["maroon"]),
    (a["bewildering"], c["green"]),
    (a["bewildering"], c["purple"]),
    (a["bewildering"], c["lime"]),
    (a["bewildering"], c["dark green"]),
    (a["bewildering"], c["blue"]),
    (a["bewildering"], c["gold"]),

    (a["bitter"], c["brown"]),
    (a["bitter"], c["yellow"]),
    (a["bitter"], c["white"]),
    (a["bitter"], c["dark grey"]),
    (a["bitter"], c["grey"]),
    (a["bitter"], c["lime"]),

    (a["blush"], c["pink"]),
    (a["blush"], c["red"]),

    (a["bold"], c["pink"]),
    (a["bold"], c["magenta"]),
    (a["bold"], c["orange"]),
    (a["bold"], c["brown"]),
    (a["bold"], c["yellow"]),
    (a["bold"], c["black"]),
    (a["bold"], c["red"]),
    (a["bold"], c["cyan"]),
    (a["bold"], c["maroon"]),
    (a["bold"], c["green"]),
    (a["bold"], c["purple"]),
    (a["bold"], c["lime"]),
    (a["bold"], c["blue"]),
    (a["bold"], c["gold"]),

    (a["brash"], c["pink"]),
    (a["brash"], c["magenta"]),
    (a["brash"], c["silver"]),
    (a["brash"], c["brown"]),
    (a["brash"], c["black"]),
    (a["brash"], c["red"]),
    (a["brash"], c["dark grey"]),
    (a["brash"], c["maroon"]),
    (a["brash"], c["grey"]),
    (a["brash"], c["green"]),
    (a["brash"], c["purple"]),
    (a["brash"], c["lime"]),
    (a["brash"], c["dark green"]),
    (a["brash"], c["blue"]),
    (a["brash"], c["gold"]),

    (a["bright"], c["pink"]),
    (a["bright"], c["magenta"]),
    (a["bright"], c["silver"]),
    (a["bright"], c["orange"]),
    (a["bright"], c["yellow"]),
    (a["bright"], c["red"]),
    (a["bright"], c["white"]),
    (a["bright"], c["cyan"]),
    (a["bright"], c["grey"]),
    (a["bright"], c["green"]),
    (a["bright"], c["purple"]),
    (a["bright"], c["lime"]),
    (a["bright"], c["blue"]),
    (a["bright"], c["gold"]),

    (a["brilliant"], c["pink"]),
    (a["brilliant"], c["silver"]),
    (a["brilliant"], c["orange"]),
    (a["brilliant"], c["brown"]),
    (a["brilliant"], c["yellow"]),
    (a["brilliant"], c["black"]),
    (a["brilliant"], c["red"]),
    (a["brilliant"], c["white"]),
    (a["brilliant"], c["green"]),
    (a["brilliant"], c["purple"]),
    (a["brilliant"], c["blue"]),
    (a["brilliant"], c["gold"]),

    (a["calm"], c["blue"]),

    (a["calming"], c["blue"]),

    (a["cheerful"], c["pink"]),
    (a["cheerful"], c["magenta"]),
    (a["cheerful"], c["silver"]),
    (a["cheerful"], c["orange"]),
    (a["cheerful"], c["yellow"]),
    (a["cheerful"], c["red"]),
    (a["cheerful"], c["white"]),
    (a["cheerful"], c["maroon"]),
    (a["cheerful"], c["green"]),
    (a["cheerful"], c["purple"]),
    (a["cheerful"], c["blue"]),
    (a["cheerful"], c["gold"]),

    (a["chill"], c["silver"]),
    (a["chill"], c["black"]),
    (a["chill"], c["white"]),
    (a["chill"], c["cyan"]),
    (a["chill"], c["lime"]),
    (a["chill"], c["blue"]),

    (a["chilly"], c["silver"]),
    (a["chilly"], c["black"]),
    (a["chilly"], c["white"]),
    (a["chilly"], c["cyan"]),
    (a["chilly"], c["lime"]),
    (a["chilly"], c["blue"]),

    (a["classic"], c["silver"]),
    (a["classic"], c["black"]),
    (a["classic"], c["red"]),
    (a["classic"], c["white"]),
    (a["classic"], c["blue"]),
    (a["classic"], c["gold"]),

    (a["cloudy"], c["lime"]),
    (a["cloudy"], c["white"]),

    (a["cold"], c["silver"]),
    (a["cold"], c["white"]),
    (a["cold"], c["black"]),
    (a["cold"], c["cyan"]),
    (a["cold"], c["dark grey"]),
    (a["cold"], c["grey"]),
    (a["cold"], c["blue"]),
    (a["cold"], c["gold"]),

    (a["confident"], c["pink"]),
    (a["confident"], c["magenta"]),
    (a["confident"], c["silver"]),
    (a["confident"], c["orange"]),
    (a["confident"], c["brown"]),
    (a["confident"], c["yellow"]),
    (a["confident"], c["black"]),
    (a["confident"], c["red"]),
    (a["confident"], c["white"]),
    (a["confident"], c["cyan"]),
    (a["confident"], c["dark grey"]),
    (a["confident"], c["maroon"]),
    (a["confident"], c["grey"]),
    (a["confident"], c["green"]),
    (a["confident"], c["purple"]),
    (a["confident"], c["lime"]),
    (a["confident"], c["dark green"]),
    (a["confident"], c["blue"]),
    (a["confident"], c["gold"]),

    (a["cool"], c["silver"]),
    (a["cool"], c["yellow"]),
    (a["cool"], c["black"]),
    (a["cool"], c["white"]),
    (a["cool"], c["cyan"]),
    (a["cool"], c["grey"]),
    (a["cool"], c["green"]),
    (a["cool"], c["lime"]),
    (a["cool"], c["dark green"]),
    (a["cool"], c["blue"]),
    (a["cool"], c["gold"]),

    (a["cosmic"], c["black"]),
    
    (a["cosy"], c["brown"]),

    (a["crisp"], c["silver"]),
    (a["crisp"], c["white"]),
    (a["crisp"], c["lime"]),
    (a["crisp"], c["blue"]),
    (a["crisp"], c["gold"]),

    (a["crispy"], c["brown"]),
    (a["crispy"], c["yellow"]),
    (a["crispy"], c["gold"]),

    (a["curious"], c["pink"]),
    (a["curious"], c["magenta"]),
    (a["curious"], c["silver"]),
    (a["curious"], c["orange"]),
    (a["curious"], c["brown"]),
    (a["curious"], c["yellow"]),
    (a["curious"], c["black"]),
    (a["curious"], c["red"]),
    (a["curious"], c["white"]),
    (a["curious"], c["cyan"]),
    (a["curious"], c["dark grey"]),
    (a["curious"], c["maroon"]),
    (a["curious"], c["grey"]),
    (a["curious"], c["green"]),
    (a["curious"], c["purple"]),
    (a["curious"], c["lime"]),
    (a["curious"], c["dark green"]),
    (a["curious"], c["blue"]),
    (a["curious"], c["gold"]),

    (a["dainty"], c["pink"]),
    (a["dainty"], c["magenta"]),
    (a["dainty"], c["silver"]),
    (a["dainty"], c["orange"]),
    (a["dainty"], c["yellow"]),
    (a["dainty"], c["gold"]),

    (a["dank"], c["green"]),
    (a["dank"], c["dark green"]),

    (a["daring"], c["pink"]),
    (a["daring"], c["magenta"]),
    (a["daring"], c["silver"]),
    (a["daring"], c["orange"]),
    (a["daring"], c["brown"]),
    (a["daring"], c["yellow"]),
    (a["daring"], c["black"]),
    (a["daring"], c["red"]),
    (a["daring"], c["white"]),
    (a["daring"], c["cyan"]),
    (a["daring"], c["dark grey"]),
    (a["daring"], c["maroon"]),
    (a["daring"], c["grey"]),
    (a["daring"], c["green"]),
    (a["daring"], c["purple"]),
    (a["daring"], c["lime"]),
    (a["daring"], c["dark green"]),
    (a["daring"], c["blue"]),
    (a["daring"], c["gold"]),

    (a["dazzling"], c["pink"]),
    (a["dazzling"], c["magenta"]),
    (a["dazzling"], c["silver"]),
    (a["dazzling"], c["orange"]),
    (a["dazzling"], c["yellow"]),
    (a["dazzling"], c["red"]),
    (a["dazzling"], c["white"]),
    (a["dazzling"], c["cyan"]),
    (a["dazzling"], c["green"]),
    (a["dazzling"], c["blue"]),
    (a["dazzling"], c["gold"]),

    (a["deep"], c["magenta"]),
    (a["deep"], c["silver"]),
    (a["deep"], c["brown"]),
    (a["deep"], c["black"]),
    (a["deep"], c["dark grey"]),
    (a["deep"], c["maroon"]),
    (a["deep"], c["grey"]),
    (a["deep"], c["purple"]),
    (a["deep"], c["dark green"]),
    (a["deep"], c["blue"]),

    (a["delicate"], c["pink"]),
    (a["delicate"], c["silver"]),
    (a["delicate"], c["orange"]),
    (a["delicate"], c["yellow"]),
    (a["delicate"], c["white"]),
    (a["delicate"], c["cyan"]),
    (a["delicate"], c["dark grey"]),
    (a["delicate"], c["maroon"]),
    (a["delicate"], c["grey"]),
    (a["delicate"], c["green"]),
    (a["delicate"], c["dark green"]),

    (a["distinctive"], c["pink"]),
    (a["distinctive"], c["magenta"]),
    (a["distinctive"], c["silver"]),
    (a["distinctive"], c["orange"]),
    (a["distinctive"], c["brown"]),
    (a["distinctive"], c["yellow"]),
    (a["distinctive"], c["black"]),
    (a["distinctive"], c["red"]),
    (a["distinctive"], c["white"]),
    (a["distinctive"], c["cyan"]),
    (a["distinctive"], c["dark grey"]),
    (a["distinctive"], c["maroon"]),
    (a["distinctive"], c["grey"]),
    (a["distinctive"], c["green"]),
    (a["distinctive"], c["purple"]),
    (a["distinctive"], c["lime"]),
    (a["distinctive"], c["dark green"]),
    (a["distinctive"], c["blue"]),
    (a["distinctive"], c["gold"]),

    (a["dramatic"], c["pink"]),
    (a["dramatic"], c["magenta"]),
    (a["dramatic"], c["silver"]),
    (a["dramatic"], c["orange"]),
    (a["dramatic"], c["yellow"]),
    (a["dramatic"], c["black"]),
    (a["dramatic"], c["red"]),
    (a["dramatic"], c["white"]),
    (a["dramatic"], c["cyan"]),
    (a["dramatic"], c["maroon"]),
    (a["dramatic"], c["green"]),
    (a["dramatic"], c["purple"]),
    (a["dramatic"], c["lime"]),
    (a["dramatic"], c["blue"]),
    (a["dramatic"], c["gold"]),

    (a["dreamy"], c["pink"]),
    (a["dreamy"], c["magenta"]),
    (a["dreamy"], c["silver"]),
    (a["dreamy"], c["black"]),
    (a["dreamy"], c["white"]),
    (a["dreamy"], c["dark grey"]),
    (a["dreamy"], c["grey"]),
    (a["dreamy"], c["purple"]),
    (a["dreamy"], c["lime"]),
    (a["dreamy"], c["blue"]),
    (a["dreamy"], c["gold"]),

    (a["earthy"], c["brown"]),
    (a["earthy"], c["gold"]),

    (a["elegant"], c["pink"]),
    (a["elegant"], c["magenta"]),
    (a["elegant"], c["silver"]),
    (a["elegant"], c["orange"]),
    (a["elegant"], c["brown"]),
    (a["elegant"], c["yellow"]),
    (a["elegant"], c["black"]),
    (a["elegant"], c["red"]),
    (a["elegant"], c["white"]),
    (a["elegant"], c["cyan"]),
    (a["elegant"], c["dark grey"]),
    (a["elegant"], c["maroon"]),
    (a["elegant"], c["grey"]),
    (a["elegant"], c["green"]),
    (a["elegant"], c["purple"]),
    (a["elegant"], c["lime"]),
    (a["elegant"], c["dark green"]),
    (a["elegant"], c["blue"]),
    (a["elegant"], c["gold"]),

    (a["enchanting"], c["silver"]),
    (a["enchanting"], c["gold"]),

    (a["energetic"], c["pink"]),
    (a["energetic"], c["magenta"]),
    (a["energetic"], c["silver"]),
    (a["energetic"], c["orange"]),
    (a["energetic"], c["black"]),
    (a["energetic"], c["red"]),
    (a["energetic"], c["white"]),
    (a["energetic"], c["cyan"]),
    (a["energetic"], c["green"]),
    (a["energetic"], c["purple"]), 
    (a["energetic"], c["lime"]),
    (a["energetic"], c["blue"]),
    (a["energetic"], c["gold"]),

    (a["expressive"], c["pink"]),
    (a["expressive"], c["magenta"]),
    (a["expressive"], c["silver"]),
    (a["expressive"], c["orange"]),
    (a["expressive"], c["brown"]),
    (a["expressive"], c["yellow"]),
    (a["expressive"], c["black"]),
    (a["expressive"], c["red"]),
    (a["expressive"], c["white"]),
    (a["expressive"], c["cyan"]),
    (a["expressive"], c["dark grey"]),
    (a["expressive"], c["maroon"]),
    (a["expressive"], c["grey"]),
    (a["expressive"], c["green"]),
    (a["expressive"], c["purple"]),
    (a["expressive"], c["lime"]),
    (a["expressive"], c["dark green"]),
    (a["expressive"], c["blue"]),
    (a["expressive"], c["gold"]),

    (a["exquisite"], c["pink"]),
    (a["exquisite"], c["magenta"]),
    (a["exquisite"], c["silver"]),
    (a["exquisite"], c["orange"]),
    (a["exquisite"], c["brown"]),
    (a["exquisite"], c["yellow"]),
    (a["exquisite"], c["black"]),
    (a["exquisite"], c["red"]),
    (a["exquisite"], c["white"]),
    (a["exquisite"], c["cyan"]),
    (a["exquisite"], c["dark grey"]),
    (a["exquisite"], c["maroon"]),
    (a["exquisite"], c["grey"]),
    (a["exquisite"], c["green"]),
    (a["exquisite"], c["purple"]),
    (a["exquisite"], c["lime"]),
    (a["exquisite"], c["dark green"]),
    (a["exquisite"], c["blue"]),
    (a["exquisite"], c["gold"]),

    (a["fancy"], c["pink"]),
    (a["fancy"], c["magenta"]),
    (a["fancy"], c["silver"]),
    (a["fancy"], c["orange"]),
    (a["fancy"], c["brown"]),
    (a["fancy"], c["yellow"]),
    (a["fancy"], c["black"]),
    (a["fancy"], c["red"]),
    (a["fancy"], c["white"]),
    (a["fancy"], c["cyan"]),
    (a["fancy"], c["dark grey"]),
    (a["fancy"], c["maroon"]),
    (a["fancy"], c["grey"]),
    (a["fancy"], c["green"]),
    (a["fancy"], c["purple"]),
    (a["fancy"], c["lime"]),
    (a["fancy"], c["dark green"]),
    (a["fancy"], c["blue"]),
    (a["fancy"], c["gold"]),


    (a["fierce"], c["pink"]),
    (a["fierce"], c["magenta"]),
    (a["fierce"], c["silver"]),
    (a["fierce"], c["orange"]),
    (a["fierce"], c["brown"]),
    (a["fierce"], c["yellow"]),
    (a["fierce"], c["black"]),
    (a["fierce"], c["red"]),
    (a["fierce"], c["white"]),
    (a["fierce"], c["cyan"]),
    (a["fierce"], c["dark grey"]),
    (a["fierce"], c["maroon"]),
    (a["fierce"], c["grey"]),
    (a["fierce"], c["green"]),
    (a["fierce"], c["purple"]),
    (a["fierce"], c["lime"]),
    (a["fierce"], c["dark green"]),
    (a["fierce"], c["blue"]),
    (a["fierce"], c["gold"]),

    (a["fiery"], c["pink"]),
    (a["fiery"], c["magenta"]),
    (a["fiery"], c["yellow"]),
    (a["fiery"], c["red"]),
    (a["fiery"], c["white"]),

    (a["fresh"], c["pink"]),
    (a["fresh"], c["magenta"]),
    (a["fresh"], c["silver"]),
    (a["fresh"], c["orange"]),
    (a["fresh"], c["brown"]),
    (a["fresh"], c["yellow"]),
    (a["fresh"], c["black"]),
    (a["fresh"], c["red"]),
    (a["fresh"], c["white"]),
    (a["fresh"], c["cyan"]),
    (a["fresh"], c["dark grey"]),
    (a["fresh"], c["maroon"]),
    (a["fresh"], c["grey"]),
    (a["fresh"], c["green"]),
    (a["fresh"], c["purple"]),
    (a["fresh"], c["lime"]),
    (a["fresh"], c["dark green"]),
    (a["fresh"], c["blue"]),
    (a["fresh"], c["gold"]),

    (a["frosty"], c["pink"]),
    (a["frosty"], c["magenta"]),
    (a["frosty"], c["silver"]),
    (a["frosty"], c["orange"]),
    (a["frosty"], c["brown"]),
    (a["frosty"], c["yellow"]),
    (a["frosty"], c["black"]),
    (a["frosty"], c["red"]),
    (a["frosty"], c["white"]),
    (a["frosty"], c["cyan"]),
    (a["frosty"], c["dark grey"]),
    (a["frosty"], c["maroon"]),
    (a["frosty"], c["grey"]),
    (a["frosty"], c["green"]),
    (a["frosty"], c["purple"]),
    (a["frosty"], c["lime"]),
    (a["frosty"], c["dark green"]),
    (a["frosty"], c["blue"]),
    (a["frosty"], c["gold"]),

    (a["funky"], c["pink"]),
    (a["funky"], c["magenta"]),
    (a["funky"], c["silver"]),
    (a["funky"], c["orange"]),
    (a["funky"], c["brown"]),
    (a["funky"], c["yellow"]),
    (a["funky"], c["black"]),
    (a["funky"], c["red"]),
    (a["funky"], c["white"]),
    (a["funky"], c["cyan"]),
    (a["funky"], c["dark grey"]),
    (a["funky"], c["maroon"]),
    (a["funky"], c["grey"]),
    (a["funky"], c["green"]),
    (a["funky"], c["purple"]),
    (a["funky"], c["lime"]),
    (a["funky"], c["dark green"]),
    (a["funky"], c["blue"]),
    (a["funky"], c["gold"]),

    (a["gleaming"], c["pink"]),
    (a["gleaming"], c["magenta"]),
    (a["gleaming"], c["silver"]),
    (a["gleaming"], c["orange"]),
    (a["gleaming"], c["brown"]),
    (a["gleaming"], c["yellow"]),
    (a["gleaming"], c["black"]),
    (a["gleaming"], c["red"]),
    (a["gleaming"], c["white"]),
    (a["gleaming"], c["cyan"]),
    (a["gleaming"], c["dark grey"]),
    (a["gleaming"], c["maroon"]),
    (a["gleaming"], c["grey"]),
    (a["gleaming"], c["green"]),
    (a["gleaming"], c["purple"]),
    (a["gleaming"], c["lime"]),
    (a["gleaming"], c["dark green"]),
    (a["gleaming"], c["blue"]),
    (a["gleaming"], c["gold"]),

    (a["glistening"], c["pink"]),
    (a["glistening"], c["magenta"]),
    (a["glistening"], c["silver"]),
    (a["glistening"], c["orange"]),
    (a["glistening"], c["brown"]),
    (a["glistening"], c["yellow"]),
    (a["glistening"], c["black"]),
    (a["glistening"], c["red"]),
    (a["glistening"], c["white"]),
    (a["glistening"], c["cyan"]),
    (a["glistening"], c["dark grey"]),
    (a["glistening"], c["maroon"]),
    (a["glistening"], c["grey"]),
    (a["glistening"], c["green"]),
    (a["glistening"], c["purple"]),
    (a["glistening"], c["lime"]),
    (a["glistening"], c["dark green"]),
    (a["glistening"], c["blue"]),
    (a["glistening"], c["gold"]),

    (a["glorious"], c["pink"]),
    (a["glorious"], c["magenta"]),
    (a["glorious"], c["silver"]),
    (a["glorious"], c["orange"]),
    (a["glorious"], c["brown"]),
    (a["glorious"], c["yellow"]),
    (a["glorious"], c["black"]),
    (a["glorious"], c["red"]),
    (a["glorious"], c["white"]),
    (a["glorious"], c["cyan"]),
    (a["glorious"], c["dark grey"]),
    (a["glorious"], c["maroon"]),
    (a["glorious"], c["grey"]),
    (a["glorious"], c["green"]),
    (a["glorious"], c["purple"]),
    (a["glorious"], c["lime"]),
    (a["glorious"], c["dark green"]),
    (a["glorious"], c["blue"]),
    (a["glorious"], c["gold"]),

    (a["glossy"], c["pink"]),
    (a["glossy"], c["magenta"]),
    (a["glossy"], c["silver"]),
    (a["glossy"], c["orange"]),
    (a["glossy"], c["brown"]),
    (a["glossy"], c["yellow"]),
    (a["glossy"], c["black"]),
    (a["glossy"], c["red"]),
    (a["glossy"], c["white"]),
    (a["glossy"], c["cyan"]),
    (a["glossy"], c["dark grey"]),
    (a["glossy"], c["maroon"]),
    (a["glossy"], c["grey"]),
    (a["glossy"], c["green"]),
    (a["glossy"], c["purple"]),
    (a["glossy"], c["lime"]),
    (a["glossy"], c["dark green"]),
    (a["glossy"], c["blue"]),
    (a["glossy"], c["gold"])
]
